config/routes.rb
Rails.application.routes.draw do
  resources :blogs, only: [:index, :show] do
    collection do
      get :top_search
    end
  end
  resources :pictures, only: [:index]
  namespace :admin do
    root to: 'employees#index'
    resources :users
    resources :categories
    resources :tags
    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
      end
    end
    resources :articles do
      collection do
        post :upload_image
      end
    end
    resources :pictures do
      collection do
        post :upload_image
      end
    end
  end

  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  devise_for :users, controllers: { sessions: "web/sessions", registrations: "web/registrations", passwords: "web/passwords" }
  
  root to: 'blogs#index'

end

app/models/article.rb
class Article < ApplicationRecord

  has_many :attachments, as: :attachment_entity
  belongs_to :category
  belongs_to :user

  def user_name
    self.user ? user.name : "jamst"
  end

  def cover_img_path
  	self.cover_img ? Attachment.find(self.cover_img.to_i).path.url : ""
  end

  def self.view_count_top
    order(view_count: :desc).limit(5)
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.page(params[:page]).per(9)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        create_attachment
        format.html { redirect_to :action=>"index" }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_attachment
    unless params[:draft_img].blank?
      attachment = Attachment.create(attachment_entity_type: "Article",attachment_entity_id: @article.id, path: params[:draft_img], created_by: 1 ) 
      @article.cover_img = attachment.id
      @article.save
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        create_attachment
        format.html { redirect_to :action=>"index" }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_image
    attachment = Attachment.create(attachment_entity_type: "Article", path: params[:wang_editor_file], created_by: 1 )
    render plain: attachment.path
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:category_id,:title,:content,:cover_img)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    #@article.attachments.create(:attachment_file => params[:payment_bill]) unless params[:payment_bill].blank?
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_image
    attachment = Attachment.create(attachment_entity_type: "Article", path: params[:wang_editor_file], created_by: 1 )
    render plain: attachment.path
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:category_id,:title,:content)
    end
end

app/views/admin/articles/_form.html.erb
<br/><br/>
<%= form_for @article, url: url, method: meth, :html => { :multipart => true } do |f| %>
  <div class="field">
    <%= file_field_tag "draft_img", id: 'draft_img' %>
  </div>

  <div class="control-group optional form-group field" style="margin-top: 10px" >
	  <%= f.label :category, 'Category', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= f.select :category_id, options_for_select(Category.all.collect { |p| [ p.name, p.id ] }, @article.category_id ), {include_blank: true}, {class: 'form-control input-sm', style: 'width: 280px;' } %>
	  </div>
  </div>

  <div class="control-group optional form-group field" style="margin-top: 10px" >
	  <%= f.label :title, 'Title', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= f.text_field :title, class: 'form-control input-sm', style: 'width: 280px;' %>
	  </div>
  </div>

  <div class="control-group optional form-group field" style="margin-top: 10px" >
	  <%= f.label :content, 'Content', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= text_area_tag 'article[content]', @article.content, style: "height: 600px;max-height: 800px"  %>
	  </div>
  </div>
  
  <div class="actions">
    <%= f.submit "提交"%>
  </div>
<% end %>


<% content_for :scripts do %>
	<%= javascript_include_tag 'wangEditor.min' %>
    <%= stylesheet_link_tag    'wangEditor.min' %>
	<script>
		//富文本编辑器初始化
		var editor = new wangEditor('article_content');
		//图片上传配置
		editor.config.uploadImgUrl = "/admin/articles/upload_image";
		editor.config.uploadImgFileName = "wang_editor_file"
		editor.config.uploadHeaders = {
		'Accept' : 'text/x-json',
		'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
		};
		editor.create();
		editor.$editorContainer.css('z-index', 0);
	</script>
<% end %>

app/views/admin/articles/_list.html.erb
<tr id="article_<%= article.id %>">
  <td class="center aligned">
    <span><%= article.id%></span>
  </td>
  <td class="center aligned">
    <%=  article.title%>
  </td>
  <td class="center aligned">
    <%= article.user_name %>
  </td>
  <td class="center aligned">
    <%= link_to edit_admin_article_path(article), data: {content: '修改', variation: 'inverted'}, class: 'ui blue icon button' do %>
      <i class="edit icon"></i>
    <% end %>
  </td>
</tr>

app/views/admin/articles/edit.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>编辑文章</h2>
  </div>
</div>
<%= render 'form', url: admin_article_path(@article), meth: :put %>

app/views/admin/articles/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>文章管理</h2>
  </div>
</div>
<%#= render 'search_form'  %>
<div class="ui blue segment">
  <div class="ui grid">
    <div class="left floated wide column">
      <%= link_to new_admin_article_path, class: 'ui primary button' do %>
        <i class="plus icon"></i>新增文章
      <% end %>
    </div>
  </div>
  <table class="ui selectable striped celled table">
    <thead>
    <tr >
      <th class="center aligned">ID</th>
      <th class="center aligned">标题</th>
      <th class="center aligned">作者</th>
      <th class="center aligned">操作</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'list', collection: @articles, as: :article %>
    </tbody>
  </table>
  <span class="blue">
    <%= page_entries_info(@articles) %>
  </span>
  <%= paginate(@articles, :theme => 'admin')%>
</div>

app/views/admin/articles/new.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>新建文章</h2>
  </div>
</div>
<%= render 'form', url: admin_articles_path, meth: :post %>

app/views/admin/articles/show.html.erb
<div class="ui blue segment">
	<h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a><%= @article.title %></h2>
	<br/><br/>
	<%= @article.content.html_safe %>
</div>