config/routes.rb
Rails.application.routes.draw do
  resources :blogs, only: [:index, :show] do
    collection do
      get :top_search
    end
  end
  resources :pictures, only: [:index]
  namespace :admin do
    root to: 'employees#index'
    resources :users
    resources :categories
    resources :tags
    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
      end
    end
    resources :articles do
      collection do
        post :upload_image
      end
    end
    resources :pictures do
      collection do
        post :upload_image
      end
    end
  end

  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  devise_for :users, controllers: { sessions: "web/sessions", registrations: "web/registrations", passwords: "web/passwords" }
  
  root to: 'blogs#index'

end

app/models/employee.rb
class Employee < ApplicationRecord

	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/admin/employees_controller.rb
# coding: utf-8
# 雇员管理
class Admin::EmployeesController < Admin::BaseController
  # before_action :authenticate_employee!, :except => [:forget_password, :reset_mail]
  # before_action :left_tab, :only => [:index]
  # before_action :set_employee, only: [:destroy]

  def index
    @html_title = "Employees"
    @employees = Employee.all
  end

  def new
    @html_title =  "New employee"
    @employee =  Employee.new
    render :layout => false
  end

  def edit
    @html_title = "Edit employee"
    @employee =  Employee.find(params[:id])
    render :layout => false
  end

  def show
    @html_title =  "Show employee"
    @employee =  Employee.find(params[:id])
    render :layout => false
  end

  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(permitted_resource_params)
        format.json { render :json=>{:success=>true} }
      else
        format.json { render :json=>{:success=>false} }
      end
    end
  end

  def create
    @employee = Employee.new
    @employee.attributes = permitted_resource_params
    if @employee.save
      flash[:success] = flash_message_for(@employee, :successfully_created)
      respond_with(@employee) do |format|
        format.html { redirect_to location_after_save }
        format.js   { render :layout => false }
      end
    else
      respond_with(@employee) do |format|
        format.html do
          flash.now[:error] = @employee.errors.full_messages.join(", ")
          render action: 'new'
        end
        format.js { render layout: false }
      end
    end
  end

  def destroy
    @employee.employee_status = params[:employee_status] if params[:employee_status]
    if @employee.save
      respond_to do |format|
        format.js
      end
    else
      respond_with(@employee) do |format|
        format.html { redirect_to location_after_destroy }
      end
    end
  end

  def location_after_destroy(options = {})
    polymorphic_url([:admin,:employees],options)
  end

  def location_after_save(options = {})
    polymorphic_url([:admin,:employees],options)
  end

  def permitted_resource_params
    params.require(:employee).permit!
  end

  #找回密码
  def forget_password
    return unless request.post?
    userinfo =  params[:email].strip
    employee = Employee.where("name = ? or email = ?", userinfo, userinfo)
    if employee.present? && userinfo.present?
      employee.last.send_user_mail
      redirect_to :action => "reset_mail"
    else
      flash.now[:warning]  = "Please enter the correct user name / registered mail"
    end
  end

  # 邮件重置
  def reset_mail

  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end


end

app/views/admin/employees/_list.html.erb
<tr id="<%= ajax_bar_element_id(employee) %>">
  <td class="center aligned">
    <span><%= employee.id%></span>
  </td>
  <td class="center aligned">
    <%=  employee.email%>
  </td>
  <td class="center aligned">
    <%= employee.name %>
  </td>
  <td class="center aligned">
    <%= employee.mobile %>
  </td>
  <td class="center aligned">
    <%#= employee.parent&.name %>
  </td>
  <td class="center aligned">
    <%#= link_to_with_permissions edit_admin_hr_employee_path(employee), remote: true, data: {content: '修改', variation: 'inverted'}, class: 'ui blue icon button' do %>
      <i class="edit icon"></i>
    <%# end %>
    <%#= link_to_with_permissions roles_admin_hr_employee_path(employee), data: {content: '分配角色', variation: 'inverted'}, class: 'ui green icon button' do %>
      <i class="hand pointer icon"></i>
    <% #end %>
    <%#= link_to_with_permissions edit_parent_admin_hr_employee_path(employee), remote: true, data: {content: '分配上级', variation: 'inverted'}, class: 'ui olive icon button' do %>
      <i class="share icon"></i>
    <% #end %>
  </td>
</tr>

app/views/admin/employees/_search_form.html.erb
<% if @q.present? %>
  <div class="ui blue segment">
    <%= simple_form_for @q,  url: admin_hr_employees_path, method: :get, wrapper: 'semantic_search_form' do |f| %>
      <div class="ui five column grid">
        <%= f.input :email, placeholder: '邮箱' %>
        <%= f.input :name, placeholder: '姓名' %>
        <div class="column">
          <%= f.submit '搜索', class: 'ui primary button' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/employees/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>员工管理</h2>
  </div>
</div>
<%= render 'search_form'  %>
<div class="ui blue segment">
  <div class="ui grid">
    <div class="left floated wide column">
      <%#= link_to new_admin_employee_path, remote: true, class: 'ui primary button' do %>
        <i class="plus icon"></i>新增员工
      <%# end %>
    </div>
  </div>
  <table class="ui selectable striped celled table">
    <thead>
    <tr >
      <th class="center aligned">ID</th>
      <th class="center aligned">邮箱</th>
      <th class="center aligned">姓名</th>
      <th class="center aligned">手机</th>
      <th class="center aligned">上级</th>
      <th class="center aligned">操作</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'list', collection: @employees, as: :employee %>
    </tbody>
  </table>
  <span class="blue">
    <%#= page_entries_info(@employees) %>
  </span>
  <%#= paginate(@employees, :theme => 'admin')%>
</div>